### ISSUE TITLE
Checkout will fail on first run

### ISSUE THREAD

**Issue by gagath** [neomilium/ovh-redirections#1]
In the README the user is told to run `fetch` before `checkout`. However the first fetch will fail with the following message:
```Using "mydomain.org" domain configuration…
5 redirections found, fetching details…
Redirections written to ".mydomain.org_ovh-redirections.yaml"
[Errno 2] No such file or directory: 'mydomain.org_ovh-redirections.yaml'
Maybe you missed to run './ovh-redirections checkout' before ?
```
Running the `checkout` command and then the `fetch` command solves the issue. It seems that the software is writing a file and then reopening it, maybe the file was not closed before the read.

**Comment by neomilium** [comment]
Any patch to fix it ?

**Comment by gagath** [comment]
I proposed PR #3 that identifies the problem and tries to solve it.
